def idealDayTest(values):  # Fitness function that will be passed to the abc
    temperature = values[0] + values[1]       # Calcuate the day's temperature
    humidity = values[2] * values[3]          # Calculate the day's humidity
    
    cost_temperature = abs(70 - temperature)  # Check how close the daily temperature to 70
    cost_humidity = abs(37.5 - humidity)      # Check how close the humidity is to 37.5
    
    return cost_temperature + cost_humidity   # This will be the cost of your fitness function generated by the values

         # First value      #Second Value     # Third Value     # Fourth Value
values = [('int', (0,100)), ('int', (0,100)), ('float',(0,100)), ('float', (0, 100))]

abc = ABC(fitnessFunction=idealDayTest, 
          valueRanges=values, 
          endValue=2           # Or iterationAmount
         )
abc.specifyMinOrMax('min')     # Here you are specifying you would like your fitness cost minimized
abc.runABC()
